### PR TITLE
Avoid parsing version properties as numbers

### LINKED ISSUE #1980: [BUG] some version numbers parsed as float
**Describe the bug**
Versions in properties files that have a trailing zero in the minor component and no patch component are parsed as floats, resulting in an incorrect version.

Examples:
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L972
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1025
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1224
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1224
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/go.amazon.properties#L46

**To Reproduce**
Visible in UI. Example showing Go 1.10 mislabeled as 1.1.

image

**Expected behavior**
Versions should retain trailing zeros.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: firefox
 - Version: 76.0.1

**Additional context**

Possible option to avoid this would be to change
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/lib/utils.js#L205
to
```js
if (prop.match(/^-?[0-9]*\.[0-9]+[^0]$/)) return parseFloat(prop);
```
so that it does not match numbers with a trailing zero. This may result in missing some numbers that should be parsed as floats. In my limited testing I didn't find any properties other than versions being excluded.

### PR DESCRIPTION
**Pull request by vcabbage**
Parsing versions such as "1.10" results in a "1.1" float, incorrectly
changing the value.

Fixes #1980

### CODE REVIEW

**Comment by vcabbage** [comment]
> Maybe a hack that checks the keyname if its version or semver could work, but it won't be pretty either.

@partouf Is this what you had in mind?

**Comment by partouf** [comment]
> > Maybe a hack that checks the keyname if its version or semver could work, but it won't be pretty either.
> 
> @partouf Is this what you had in mind?

Yes, looks good! Also tests, great!

Waiting for someone else to verify that this is acceptable

File: test/properties-test.js [hunk 1]
```diff
@@ -151,6 +151,12 @@ describe('Properties', () => {
         compilerProps.get(languages, 'bar', true, undefined).should.deep.equal({a: false});
         compilerProps.propsByLangId[languages.a.id] = undefined;
     });
+    it('should not parse version properies as numbers', () => {
+        should.equal(casesProps('libs.example.versions.010.version'), '0.10');
```
Comment (apmorton) [inline test/properties-test.js:155]: should.equal uses coercive equality comparison, so these tests will probably succeed even if the prop is parsed as a number since `0.1 == '0.10'` in JavaScript.

You should use `should.strictEqual` instead.

Comment (vcabbage) [reply test/properties-test.js:155]: `strictEqual` doesn't seem to be a method on `should`. Seems to be a difference between the [`assert`](https://www.chaijs.com/api/assert/#method_equal) (non-strict) and [`expect`/`should`](https://www.chaijs.com/api/bdd/#method_equal) (strict) APIs.

I've verified that the test fails without the fix.

Comment (apmorton) [reply test/properties-test.js:155]: Woops - I was incorrectly looking at the should.js doc instead of the chai.js doc.
