### PR TITLE
Fix #7852: return processRawOptRemarks back to BaseCompiler

### LINKED ISSUE #7852: Unexpected LDCCompiler.processRawOptRemarks
Sentry Issue: [COMPILER-EXPLORER-EAV](https://compiler-explorer.sentry.io/issues/6698833586/?referrer=github_integration)

```
Non-Error capture:
Context: Unexpected processRawOptRemarks call for compiler: ldc 1.40.1
Data:
""
Trace:
SentryCapture file:///infra/.deploy/lib/sentry.js:62:19
LDCCompiler.processRawOptRemarks file:///infra/.deploy/lib/base-compiler.js:2344:9
LDCCompiler.processOptOutput file:///infra/.deploy/lib/base-compiler.js:2355:30
async Promise.all undefined:undefined:undefined
async LDCCompiler.checkOutputFileAndDoPostProcess file:///infra/.deploy/lib/base-compiler.js:1369:16
undefined async file:///infra/.deploy/lib/base-compiler.js:2238:63
async env.enqueue.abandonIfStale file:///infra/.deploy/lib/base-compiler.js:2220:25
undefined async file:///infra/.deploy/node_modules/p-queue/dist/index.js:230:36
```

Seems the decision to separate processRaw OptRemarks from BaseCompiler was not a good one. I'll revert it in the near time [Ofek]

### PR DESCRIPTION
**Pull request by OfekShilon**

### CODE REVIEW

File: lib/base-compiler.ts [hunk 1]
```diff
@@ -3206,10 +3206,50 @@ export class BaseCompiler {
...
+    // LLVM opt-remark yaml processing is used by at least clang, flang, rustc and ldcc.
     processRawOptRemarks(buffer: string, compileFileName = ''): OptRemark[] {
-        // Shouldn't get here.
-        SentryCapture('', `Unexpected processRawOptRemarks call for compiler: ${this.compiler.name}`);
-        return [];
+        const output: OptRemark[] = [];
+        const remarksSet: Set<string> = new Set<string>();
+        const remarks: any = parseAllDocuments(buffer);
+
+        const DisplayOptInfo = (optInfo: OptRemark) => {
```
Comment (junlarsen) [inline lib/base-compiler.ts]: nit: rename to displayOptInfo

**Review by junlarsen — APPROVED** [review]

File: lib/base-compiler.ts (hunk 1 above)
Comment (OfekShilon) [reply lib/base-compiler.ts]: Sure. Thanks!
