### PR TITLE
Control flow graph tool rework

### LINKED ISSUE #1855: [BUG] Graph viewer slowly drifts to top left
**Describe the bug**
When the graph viewer is left alone for a while, the graph slowly drifts to the top left.

**To Reproduce**
1. Open up a Graph Viewer for any compiler output
2. Wait. The graph will slowly drift to the top left corner

**Expected behavior**
It should stay in the same place.

**Link**
If applicable, please provide a link to Compiler Explorer to help explain your problem.

**Screenshots**
Peek 2020-02-24 19-26

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 73.0

**Additional context**

### LINKED ISSUE #3142: [BUG]: Silly/annoying mouseover behaviour in Graph Viewer
### Describe the bug

Menu pops away when you get your mouse in the gap between the combobox and the popup menu.

### Steps to reproduce

Open graph viewer, try to select a different function.

### Expected behavior

Be a bit more user-friendly

### Reproduction link

Not applicable

### Screenshots

graph_weird_mouseover_behaviour

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
WIP, much left to be done:

- [x] Implement function dropdown
- [x] Zooming and panning
  - [x] ~~Proper zooming for the canvas~~ Now replaced with svg
- [x] Pane state and backwards compatibility
- [x] Syntax highlighting
- [x] Light mode
- [x] There's a weird bug with line svg widths being inconsistent
image

Future Work:
- Better handle some no-return function calls like abort or exit
- Add edges for jump tables / do some jump table parsing
- Support llvm ir
- Layout
  - Take into account tree shape when placing trees side by side
  - Better edge offset system
  - Reduce edge crossing
  - Layout compacting
- Store position in state

Currently looks like this:
image

Closes #3142 
Closes #1855

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
image

File: static/graph-layout-core.ts [hunk 1]
```diff
@@ -0,0 +1,742 @@
...
+                        blockedColumns
+                            .slice(0, sourceColumn)
+                            .reverse()
+                            .findIndex(v => v < topRow);
+                    const rightCandidate = sourceColumn + blockedColumns.slice(sourceColumn).findIndex(v => v < topRow);
+                    // hamming distance
+                    const distanceLeft =
+                        Math.abs(sourceColumn - leftCandidate) + Math.abs(sourceColumn - rightCandidate);
+                    const distanceRight =
+                        Math.abs(targetColumn - leftCandidate) + Math.abs(targetColumn - rightCandidate);
```
Comment (karliss) [inline static/graph-layout-core.ts:415]: This is wrong. Should be:
```
distanceLeft = |source-left | + |target - left|
```
not
```
distanceLeft = |source-left | + |target - right|
```
This is probably the cause for loop edges going the long way  around and up in this  image:
image

Comment (jeremy-rifkin) [reply static/graph-layout-core.ts:415]: Ope thank you!

Comment (jeremy-rifkin) [reply static/graph-layout-core.ts]: The loop edge is going the wrong way here too
image

The left and right distance should be the same, not sure how to introduce the necessary information to be able to chose the path with fewer conflicts here

Comment (karliss) [reply static/graph-layout-core.ts]: Try adding the code which talks about  figure 8 shape. It's supposed to deal with slightly different case but might help in this one as well.

**Comment by karliss** [comment]
As a fallback you should clamp the position of endpoints (or last 2 and first 2 points to keep them vertical) so that they are within the width of block.  Even if it causes edges to be closer than intended or even be at angle it's better than edges terminating in empty space.

There a few things  that can be done to reduce the chance of it happening in simple cases like this, but it's still good to have a fallback.

image

File: static/graph-layout-core.ts [hunk 2]
```diff
@@ -0,0 +1,849 @@
...
+            block.boundingBox = boundingBox;
+            block.row = 0;
+            // between immediate children
+            const [left, right] = [this.blocks[block.treeEdges[0]], this.blocks[block.treeEdges[1]]];
+            block.col = Math.floor((left.col + right.col) / 2); // TODO
+        }
+    }
+
+    assignColumns(topologicalOrder) {
+        // Note: Currently not taking shape into account like Cutter does.
```
Comment (karliss) [inline static/graph-layout-core.ts:302]: Skipping full shape based side by side placement this might be fine. Typical function size in compiler explorer probably won't be as big as when doing reverse engineering.  Also with the compacting step (which you currently don't have) fullshape  based placement is somewhat redundant.  So it might be better to start with that. Although that's also a big nasty piece of code, maybe less if you used of the shelf LP solver.

**Comment by karliss** [comment]
With regards to edge offset calculation and the order in which it is done. It solves two problems:
* reduce edge crossings
* tight curve placement

A lot of complexity comes from the second goal and it's possible to make a slightly simpler version which solves only the first part. I would like to see at least that much.

Tight curve placement at this stage would also be somewhat redundant if the compacting step was implemented.

 I will try to make some drawings better give you a better understanding of what's going on there. Since the documention in Cutter doesn't go into too much details about that part.

File: static/panes/cfg-view.interfaces.ts [hunk 3]
```diff
@@ -22,17 +22,7 @@
...
-export interface CfgOptions {
-    physics?: boolean;
-    navigation?: boolean;
-}
-
-export interface CfgState extends PaneState {
-    selectedFn?: string;
-    pos: vis.Position;
+export interface CfgState {
+    selectedFunction: string;
```
Comment (RubenRBS) [inline static/panes/cfg-view.interfaces.ts:26]: This change will make it incomptabile with old cfg links. No way around it?

**Comment by jeremy-rifkin** [comment]
I have an idea for reducing a lot of edge crossing: Add the edges in order of shortest first and let them greedily take the closest columns. Works well for stuff like this:
image

Not sure if this will pan out. Might end up being a disaster in a lot of cases.

I have some ideas for resolving the remaining crossing

File: static/panes/cfg-view.interfaces.ts (hunk 3 above)
Comment (jeremy-rifkin) [reply static/panes/cfg-view.interfaces.ts:26]: Thanks for the reminder, I think it's doable to provide backward compatibility here just a few extra cases to handle in the code. I'll flesh this stuff out more later.

**Comment by karliss** [comment]
> Not sure if this will pan out. Might end up being a disaster in a lot of cases.

No need to reinvent the wheel wheel (heuristics).  For cutter I already prepared a set of the them which works pretty well in practice. Length is one of them but there are a few more factors. If you already reorganized the code to be able to sort by length. Adding rest of the sorting heuristics should be as simple as adding them to sorting comparator. 

Just looked at the last code you wrote, to implement the solution I am suggesting it will be to further split it so that you can sort individual segments of edges instead of edges. Priority for some horizontal segments of edge might be different than priority for vertical ones or even different for starting and end vertical segments.

So the priority I used starting with most important was this :
* segment kind -2, -1, 0, 1, 2 (will explain later) 
* length of segment
* `2*length_of_whole_edge + (target.row >= start.row ? 1 : 0)`


* Segment kind prevents these kind of crossings:
image
image
* Length of segment functions similar to edge length in situation like these, but slightly better since for proper nesting only the length off  corresponding segment matters. When using whole lenghh a long horizontal segment might ruin nesting relationship of vertical segments.
image
* whole length serves as final tiebreaker to ensure multiple parallel lines are ordered more neatly


Now the explaination of segment kinds. I categorize segments into 5 kinds based on direction of previous and next segment. Example image and description is for vertical segments but it works in similar way for horizontal ones.
* -2 U shape to the left
* -1 L shape to the left
* 0 straight vertical line
* 1 L shape to the right
* 2 U shape to the right
image


For maximum tidiness it may be necessary to flip the comparison direction of segment or whole line length based on segment kind  mostly (whether it's to the left or right).

**Comment by jeremy-rifkin** [comment]
Awesome thanks so much for the explanation! I’ll work on this more tonight

**Comment by jeremy-rifkin** [comment]
Ok let's get this merged! The base functionality should be good to go, plenty to iterate on more later.

File: static/panes/cfg-view.ts [hunk 4]
```diff
@@ -22,427 +22,323 @@
 // ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 // POSSIBILITY OF SUCH DAMAGE.
 
+import {Pane} from './pane';
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:25]: Can't comment in unmodified files, but do you think we should change `views/templates/panes/compiler.pug:64` to `Control Flow Graph`?

File: static/panes/cfg-view.ts [hunk 5]
```diff
@@ -22,427 +22,323 @@
...
+        this.eventHub.emit('requestFilters', this.compilerInfo.compilerId);
+        this.eventHub.emit('requestCompiler', this.compilerInfo.compilerId);
+        const selector = this.domRoot.get()[0].getElementsByClassName('function-selector')[0];
+        if (!(selector instanceof HTMLSelectElement)) {
+            throw new Error('.function-selector is not an HTMLSelectElement');
+        }
+        this.functionSelector = new TomSelect(selector, {
+            valueField: 'value',
+            labelField: 'title',
+            searchField: ['title'],
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:102]: I think adding `placeholder` here like in compiler-picker (https://github.com/compiler-explorer/compiler-explorer/blob/main/static/compiler-picker.ts#L98) would help convey that you can type to search

File: static/panes/cfg-view.ts [hunk 6]
```diff
@@ -22,427 +22,323 @@
...
+        this.state = state;
     }
 
-    override getInitialHTML(): string {
+    override getInitialHTML() {
         return $('#cfg').html();
     }
 
+    override getDefaultPaneName() {
+        return 'CFG';
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:118]: As I said in dc, Cypress is failing because of this change, as they are suuuper simple tests that only check for the pane name to exists in rder to say "Yes, this works". Changing https://github.com/compiler-explorer/compiler-explorer/blob/main/cypress/integration/frontend-testing.js#L21 to `CFG` should fix it

File: static/panes/cfg-view.ts [hunk 7]
```diff
@@ -22,427 +22,323 @@
...
-            });
-        };
-        nodes.forEach(node => {
-            if (node.state === 0) {
-                dfs(node);
-                node.level = 1;
-                markLevels(node);
+    override onCompileResult(compilerId: number, compiler: any, result: any) {
+        if (this.compilerInfo.compilerId !== compilerId) return;
+        //console.log(result);
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:195]: Can be removed

File: static/panes/cfg-view.ts [hunk 8]
```diff
@@ -22,427 +22,323 @@
...
-        this.eventHub.emit('requestFilters', this.compilerInfo.compilerId);
-        this.eventHub.emit('requestCompiler', this.compilerInfo.compilerId);
-
-        this.togglePhysicsButton.on('click', () => {
-            this.networkOpts.physics.enabled = this.togglePhysicsButton.hasClass('active');
-            // change only physics.enabled option to preserve current node locations
-            this.cfgVisualiser.setOptions({
-                physics: {enabled: this.networkOpts.physics.enabled},
-            });
+        this.graphContainer.addEventListener('mousedown', e => {
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:139]: Love that this works

File: static/panes/cfg-view.ts [hunk 9]
```diff
@@ -22,427 +22,323 @@
...
 
-    override onCompilerClose(compilerId: number) {
-        if (this.compilerInfo.compilerId === compilerId) {
-            // We can't immediately close as an outer loop somewhere in GoldenLayout is iterating over
-            // the hierarchy. We can't modify while it's being iterated over.
-            this.close();
-            _.defer(() => {
-                this.container.close();
-            }, this);
+    drawEdges() {
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:252]: Even though I read some of the algos you linked and the PR discuission, I'm not going to pretend I understand this code and trust you hahaha

File: static/styles/explorer.scss [hunk 10]
```diff
@@ -384,13 +383,43 @@ pre.content.wrap * {
...
+        }
+        .block-container {
+            position: absolute;
+            top: 0;
+            left: 0;
+            .block {
+                position: absolute;
+                padding: 5px;
+                display: inline-block;
+                font-family: Consolas, 'Liberation Mono', Courier, monospace;
```
Comment (RubenRBS) [inline static/styles/explorer.scss:417]: For future iterations, this might be something that could be controlled by `settings.editorsFFont`

File: static/panes/cfg-view.ts [hunk 11]
```diff
@@ -22,427 +22,323 @@
...
-                    markLevels(target);
-                }
-            });
-        };
-        nodes.forEach(node => {
-            if (node.state === 0) {
-                dfs(node);
-                node.level = 1;
-                markLevels(node);
+    override onCompileResult(compilerId: number, compiler: any, result: any) {
```
Comment (RubenRBS) [inline static/panes/cfg-view.ts:193]: These types can be more specific, see https://github.com/compiler-explorer/compiler-explorer/blob/main/static/event-map.ts#L55
It would also remove the need for the case in line 197

**Review by RubenRBS — APPROVED** [review]
It looks _great_. And the code too. Honestly the comments are minor nitpicks, at best. Again, thank you so much for this!

File: static/panes/cfg-view.ts (hunk 11 above)
Comment (RubenRBS) [reply static/panes/cfg-view.ts:193]: Ohh I see, the base pane has poor typings, filled #4365 to track that

**Comment by jeremy-rifkin** [comment]
Thank you so much @RubenRBS for the review! I'll incorporate the suggestions (and fix this merge conflict) as soon as I fix my linux machine 😬

File: static/panes/cfg-view.ts (hunk 5 above)
Comment (jeremy-rifkin) [reply static/panes/cfg-view.ts:102]: Great idea and I also added `plugins: ['dropdown_input']` like the compiler picker so the search line is less crowded

File: static/panes/cfg-view.ts (hunk 9 above)
Comment (jeremy-rifkin) [reply static/panes/cfg-view.ts:252]: I am going to add some comments here because I will probably forget how everything works otherwise :)

**Comment by jeremy-rifkin** [comment]
Thank you @RubenRBS and huge thank you @karliss! More work on the actual layout part soon :)

**Comment by dkm** [comment]
this is live :rocket:

**Review by stonigrl — COMMENTED** [review]
👍
