### PR TITLE
Fix #3839

### LINKED ISSUE #3839: [BUG]: LLVM opt pipeline view fails with Assertion error in llvm-print-after-all-parser
### Describe the bug

I get a `Assertion error in llvm-print-after-all-parser` when trying to use the LLVM opt pipeline view

### Steps to reproduce

Given
```c
int f(int n) {
    for (int i = 0; i < 8; i++) {
        n += i;
    }
    return n;
}
```
I get:
```
Assertion error in llvm-print-after-all-parser: IR Dump Before LoopDeletionPass on Parallel Loop at depth 1 containing: %4<header><latch><exiting>
```

### Expected behavior

It should compile.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Resolves #3839

### CODE REVIEW

File: lib/parsers/llvm-pass-dump-parser.ts [hunk 1]
```diff
@@ -42,14 +41,30 @@ import {logger} from '../logger';
 // TODO(jeremy-rifkin): Doe we already have an assert utility
 function assert(condition: boolean, message?: string, ...args: any[]): asserts condition {
```
Comment (matsjla) [inline lib/parsers/llvm-pass-dump-parser.ts:42]: Can grab node assert https://nodejs.org/api/assert.html
