### PR TITLE
Fix #6437: Don't try and generate cfg for incomplete (truncated) IR

### LINKED ISSUE #6437: TypeError: Cannot read properties of undefined (reading 'text')
Sentry Issue: [COMPILER-EXPLORER-CXZ](https://compiler-explorer.sentry.io/issues/5298121194/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'text')
SentryCapture Context: compile failed
  File "/infra/.deploy/lib/cfg/cfg-parsers/llvm-ir.js", line 51, in LlvmIrCfgParser.splitToFunctions
    while (asmArr.length > 0 && asmArr[i].text !== '}') {
  File "/infra/.deploy/lib/cfg/cfg.js", line 48, in Module.generateStructure
    const functions = parser.splitToFunctions(code);
  File "/infra/.deploy/lib/base-compiler.js", line 1114, in RustCompiler.generateIR
    result.cfg = cfg.generateStructure(this.compiler, ir.asm.map(line => ({ text: line.text })), true);
  File "/infra/.deploy/lib/compilers/rust.js", line 66, in RustCompiler.generateIR
    return await super.generateIR(inputFilename, newOptions, irOptions, produceCfg, filters);
  File "/infra/.deploy/lib/base-compiler.js", line 1818, in RustCompiler.doCompilation
    const [asmResult, astResult, ppResult, irResult, optPipelineResult, rustHirResult, rustMacroExpResult, toolsResult,] = await Promise.all([
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by OfekShilon**

### CODE REVIEW

File: lib/cfg/cfg-parsers/llvm-ir.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export class LlvmIrCfgParser extends BaseCFGParser {
         while (i < asmArr.length) {
             if (this.functionDefinition.test(asmArr[i].text)) {
                 const start = i;
-                while (asmArr.length > 0 && asmArr[i].text !== '}') {
+                while (i < asmArr.length - 1 && asmArr[i].text !== '}') {
```
Comment (OfekShilon) [inline lib/cfg/cfg-parsers/llvm-ir.ts:65]: This turned out to NOT be the root cause, but is an obvious bug nevertheless.

Comment (partouf) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]: not `i < asmArr.length && etc` ? why -1?

Comment (partouf) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]: `i` will never be `asmArr.length` if it's `<`

Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]:
```ts
while (i < asmArr.length && asmArr[i].text !== '}') {
// suppose i == asmArr.length-1 here
    i++;
// now i is asmArr.length
}

result.push({
    start,
    end: i,   // and this is the overflowed value pushed to result.
});
```
I think..

Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]: Maybe it would be easier to change this to a do-while loop, I don't see a situation where `i++` doesn't happen at all.

Comment (partouf) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]: ahhhhh right
if the last character is not `}`, `i` will be `asmArr.length - 1 + 1`
confusing code, but whatever

**Review by partouf — APPROVED** [review]

File: lib/cfg/cfg-parsers/llvm-ir.ts (hunk 1 above)
Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts:65]: Yeah I'll change it to do-while. Gimme a minute

**Comment by dkm** [comment]
This is live :rocket:
