### PR TITLE
Fix cfg chrome render bug

### LINKED ISSUE #4421: CFG chrome render bug
Steps to reproduce: Open https://godbolt.org/z/o8K7P19TT in chrome, zoom in/out or pan.

image

I'm on chrome 108 with a gpu, would be interested if it happens without a gpu.

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #4421

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Seems to do the job

**Review by RubenRBS — APPROVED** [review]

File: static/panes/cfg-view.ts [hunk 1]
```diff
@@ -165,7 +169,7 @@ export class Cfg extends Pane<CfgState> {
             const prevZoom = this.state.zoom;
             this.state.zoom += delta;
             if (this.state.zoom >= MINZOOM) {
-                this.graphElement.style.transform = `scale(${this.state.zoom})`;
+                this.graphElement.style.transform = `scale(${this.state.zoom})${this.extraTransforms}`;
```
Comment (partouf) [inline static/panes/cfg-view.ts:172]: https://developer.mozilla.org/en-US/docs/Web/CSS/transform only shows this multiple transforms with spaces inbetween. To me, the specs are unclear on if no space will work in every browser. Do you have a source on this?

**Review by partouf — APPROVED** [review]
