### PR TITLE
Fix #5784

### LINKED ISSUE #5784: [BUG]: In IR CFG the entry block's label isn't shown
### Describe the bug

In this example simple case: https://www.compiler-explorer.com/z/Gj5KT9861
The topmost block in the CFG has the label `loop1(long, long*, long*):`  instead of `for.body.preheader:`.

### Steps to reproduce

Visit the link.

### Expected behavior

I personally think the block's label can replace the function name - no need to display both. The function name is visible at the function selection dropdown

### Reproduction link

https://www.compiler-explorer.com/z/Gj5KT9861

### Screenshots

image

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**
Fix the name of the entry block in an IR control flow graph.

### CODE REVIEW

File: lib/cfg/cfg-parsers/llvm-ir.ts [hunk 1]
```diff
@@ -83,21 +83,21 @@ export class LlvmIrCfgParser extends BaseCFGParser {
         while (i < fn.end) {
             const match = code[i].text.match(this.labelRe);
             if (match) {
+                const label = match[1];
                 if (bbStart === i) {
-                    // for -emit-llvm the first basic block doesn't have a label, for the ir viewer it does though
                     assert(result.length === 0);
-                    bbStart = i + 1;
+                    // Make the first block name fnName + label
+                    currentName += '\n' + label;
```
Comment (jeremy-rifkin) [inline lib/cfg/cfg-parsers/llvm-ir.ts:90]: This is probably ok for now but it occurs to me that making the block name itself fnName + label might not be fully adequate. What if there's a branch to the entry block's label?

Maybe it could make sense to have the entry block appear as its own basic block and just have the function label's block through to it, or maybe we could add special casing for basic blocks with multi-line names during the lookup process.

**Review by jeremy-rifkin — COMMENTED** [review]
I think the changes look good to me for now but I commented below about a case that might need more handling. Happy to merge this first iteration though if you'd prefer to defer that until later :)

File: lib/cfg/cfg-parsers/llvm-ir.ts (hunk 1 above)
Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts:90]: Right, this case didn't occur to me (partly because I never came across it). This PR as-is doesn't make things any worse for this case, but I'd be happy to try and tackle this. Please hold merging it for now.

Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts:90]: I think I'd prefer *not* to add an artificial function-name-only entry block. Did I understand correctly your first suggestion?
I'll probably be able to make the branch-target search account for multi-line block names.

Comment (OfekShilon) [reply lib/cfg/cfg-parsers/llvm-ir.ts]: Updated with something along these lines. All node IDs are now strictly labels, and there's a 'prefix' hook used just for display of the entry block.

**Comment by jeremy-rifkin** [comment]
I think looks good to me!
