### PR TITLE
Fix resize bug

### LINKED ISSUE #3616: [BUG]: Dragging a compiler pane tab loses the bottom panel
### Describe the bug

See title

Probably a recent regression, feels like the kind of thing someone would notice pretty fast.

### Steps to reproduce

- Grab a compiler pane tab
- Put it back in its original location
- Observe the absense of Output (0/1) panel at compiler tab's bottom

A quick f5 makes the site repair itself.

### Expected behavior

No visual change

### Reproduction link

Not applicable

### Screenshots

Before:
image
Drag it like this:
image
After:
image
(Ignore the broken sponsors pane, that's just because I resized the window so the screenshot size is reasonable. The same issue reproduces on normal window sizes too.)

### Operating System

Lubuntu 21.10

### Browser version

Firefox 99

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
This fixes #3616.

Printbugging triage:
```js
1651639870337 resize <-- w: 1277 h: 638 top: 70 bottom: 32 // resize information before drag
1651639879099 resize <-- w: 1277 h: 638 top: 0 bottom: 0   // drag
1651639881524 resize <-- w: 1277 h: 638 top: 0 bottom: 0   // drop
1651639883889 resize <-- w: 1277 h: 637 top: 70 bottom: 32 // first resize after drop (e.g. by resizing the window)
```

I guess somehow there's no `outerHeight` for these when golden layout is dragging them around, not sure why. What I've done to fix is `_.defer` in the resize function. The compiler and executor panes are directly affected and then I've made the change in pane.ts too for any other and all future panels.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Oh. Then this must have been happening for a while! Nice work finding the cause :)

**Comment by mattgodbolt** [comment]
Wow! Amazing detective work. Thanks!

File: static/panes/executor.js [hunk 1]
```diff
@@ -158,21 +158,23 @@ Executor.prototype.undefer = function () {
 };
 
 Executor.prototype.resize = function () {
-    var topBarHeight = utils.updateAndCalcTopBarHeight(this.domRoot, $(this.topBar[0]), this.hideable);
+    _.defer(function (self) {
```
Comment (mattgodbolt) [inline static/panes/executor.js:161]: (aside!) We really should start using our transpilation options to open the door to `() => {}` style functions

**Review by mattgodbolt — APPROVED** [review]
