### PR TITLE
fix remote libraries listing backend and frontend

### LINKED ISSUE #7590: [BUG]: Libraries not available for C++ compilers on GPU instances
It seems that libraries are not available for nvc++ compilers.

Logging from (normal amd64 instance) startup:
```
info: Fetching remote libraries from https://godbolt.org:443/winprod/api/libraries/c++ 
info: Fetching remote libraries from https://godbolt.org:443/winprod/api/libraries/c 
info: Fetching remote libraries from https://godbolt.org:443/gpu/api/libraries/cuda
```

It is expected to also show fetching libraries from `https://godbolt.org:443/gpu/api/libraries/c++`, but that does not happen for some reason.

### PR DESCRIPTION
**Pull request by partouf**
Fixes #7590

Ugly code duplication was a bit annoying

### CODE REVIEW

**Comment by partouf** [comment]
Should make both frontend and backend tests at least to verify these work the same, maybe?

**Comment by partouf** [comment]
Now that I added tests, I will just delete most of it and rewrite it to just a shared function...

**Comment by partouf** [comment]
Refactored so that there's only 1 version of the function and kept the unittests.
(uses regex version of replace instead of replaceAll because of browser compatibility etc)

File: lib/options-handler.ts [hunk 1]
```diff
@@ -397,9 +393,9 @@ export class ClientOptionsHandler {
     }
 
     async getRemoteLibraries(language: LanguageKey, remoteUrl: string) {
-        const remoteId = this.getRemoteId(remoteUrl, language);
+        const remoteId = getRemoteId(remoteUrl, language);
         if (!this.remoteLibs[remoteId]) {
-            return new Promise(resolve => {
+            return await new Promise(resolve => {
```
Comment (partouf) [inline lib/options-handler.ts:398]: I added await here to avoid duplicate work, as `this.remoteLibs[remoteId]` is not directly populated

File: static/lib-utils.ts [hunk 2]
```diff
@@ -22,19 +22,15 @@
...
 const LIB_MATCH_RE = /([\w-]*)\.([\w-]*)/i;
 
-function getRemoteId(language: string, remoteUrl: string): string {
-    const url: URL = new URL(remoteUrl);
-    return url.host.replace(/\./g, '_') + '_' + language;
-}
-
 function getRemoteLibraries(language: string, remoteUrl: string): LanguageLibs {
-    const remoteId = getRemoteId(language, remoteUrl);
+    const remoteId = getRemoteId(remoteUrl, language);
```
Comment (partouf) [inline static/lib-utils.ts:33]: Reversed order from original, huray, c'est la vie. We also can't really used types to enforce order so that sucks even more. Oh Well

**Comment by partouf** [comment]
now live
