### PR TITLE
Fix for msvc library issue

### LINKED ISSUE #3412: [BUG]: Internal Compiler Explorer error: TypeError: Cannot set properties of undefined (setting 'name') for MSVC compilers
### Describe the bug

No assembly output for the MSVC compiler. Instead we get:
```
Internal Compiler Explorer error: TypeError: Cannot set properties of undefined (setting 'name')
    at Win32VcCompiler.findLibVersion (C:\compiler-explorer\lib\base-compiler.js:461:21)
    at C:\compiler-explorer\lib\base-compiler.js:634:39
    at Proxy.map (C:\compiler-explorer\node_modules\underscore\modules\map.js:13:22)
    at Win32VcCompiler.getIncludeArguments (C:\compiler-explorer\lib\base-compiler.js:633:28)
    at Win32VcCompiler.prepareArguments (C:\compiler-explorer\lib\compilers\win32.js:96:34)
    at Win32VcCompiler.doCompilation (C:\compiler-explorer\lib\base-compiler.js:1245:18)
    at C:\compiler-explorer\lib\base-compiler.js:1650:52
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:163:29)
Compiler returned: -1
```

Tested with
- Mozilla Firefox 97.0.1
- Chromium 98.0.4758.102 Arch Linux

### Steps to reproduce

1. Visit https://godbolt.org/z/hGb7Wh1zf
2. See the error in the output window for windows

### Expected behavior

No internal compiler explorer error.

### Reproduction link

https://godbolt.org/z/hGb7Wh1zf

### Screenshots

Not applicable

### Operating System

Linux 5.16.11-2-MANJARO x86_64

### Browser version

Mozilla Firefox 97.0.1

### PR DESCRIPTION
**Pull request by partouf**
Problem:
In 2021 I tried to fix the problem of producing extremely large client-options.js files, because all the supported libraries got listed per library. We decided that there should be only 1 list of libraries and then have exceptions per compiler.
(https://github.com/compiler-explorer/compiler-explorer/commit/e24f724e47bcdc1e4acc7c62036a32282dc4e8af)

This saved a lot of megabytes, but obviously I somehow forgot about the fact that the Microsoft compilers would mess up this logic. Unfortunately this didn't show up asap, because the version of CE that Microsoft had was ancient and somehow it worked better. Until Microsoft updated to latest and didn't mention the libraries anymore per compiler, and we're now faced with a mismatch of the libraries that we have and disregarding the libraries that the Microsoft remote has.

Solution:
I think I figured out a solution where all we need to do is update our frontend, that way we don't mess up too much and we don't have to rely on other things.

So; if a compiler is a remote (this is information available in our client-options) - we instead query the libraries API of the remote. We use those libraries as the basic set of supported libraries for that compiler.

Fixes #3412

TODO
- [x] Test locally
- [x] There's more things that call these library functions, those should be updated as well
- [ ] Test on staging

### CODE REVIEW

**Comment by partouf** [comment]
it seems it's a lot more complicated than this, because fetching the remote libraries is an async action..

**Comment by partouf** [comment]
Solved async issue by fetching remote libraries on startup and putting them into client-options

File: lib/options-handler.js [hunk 1]
```diff
@@ -277,7 +282,48 @@ export class ClientOptionsHandler {
         return '9999999.99999.999';
     }
 
-    setCompilers(compilers) {
+    getRemoteId(remoteUrl, language) {
+        const url = new URL(remoteUrl);
+        return url.host.replace(/\./g, '_') + '_' + language;
+    }
```
Comment (RubenRBS) [inline lib/options-handler.js:288]: You already added this one lib-utils

Comment (partouf) [reply lib/options-handler.js:288]: yes, but that's static frontend code.. i think theres a way to share code between the two, will see if i can do that

Comment (RubenRBS) [reply lib/options-handler.js:288]: Oh! I did not realize this was not already the case, I must have confused it for another shared part, sorry!

Comment (partouf) [reply lib/options-handler.js:288]: Don't think there is a way to currently do it. I'll keep it as is for now.

File: lib/options-handler.js [hunk 2]
```diff
@@ -277,7 +282,55 @@ export class ClientOptionsHandler {
...
+
+    async getRemoteLibraries(language, remoteUrl) {
+        const remoteId = this.getRemoteId(remoteUrl, language);
+        if (!this.remoteLibs[remoteId]) {
+            return new Promise((resolve) => {
+                const url = remoteUrl + '/api/libraries/' + language;
+                logger.info(`Fetching remote libraries from ${url}`);
+                let fullData = '';
+                https.get(url, (res) => {
```
Comment (mattgodbolt) [inline lib/options-handler.js:312]: We should find an easier way to do this (not in this PR!) but surely there's some node.js async-able library to fetch JSON data :)

**Review by mattgodbolt — APPROVED** [review]
Looks good to me. Unfortunate regex-fu needed, but also not too easy to fix in a better way! Thanks for doing this!

**Comment by mattgodbolt** [comment]
Now live!

File: lib/options-handler.js (hunk 2 above)
Comment (RubenRBS) [reply lib/options-handler.js:312]: With a bit of luck, for the next LTS we get `https://github.com/nodejs/node/pull/41749` not in experimental mode and can just use `fetch` :)
