### PR TITLE
Ada: Fix inputFileName at incorrect loc for binary and execution

### LINKED ISSUE #3709: Ada compile to binary and execution broken
I teach computer science and I am using godbolt to share codes in different languages. In the last semester all ADA code was running fine. I was checking the material for this semester and I noticed that ADA code is not running. It shows the following message:
_try "gnatmake --help" for more information.
Compiler did not produce an executable_

Link: https://godbolt.org/z/dY49hPeWf

I am trying the Tree version, but still not working.

Any help?
Thanks.

_Originally posted by @jhkhouri62 in https://github.com/compiler-explorer/compiler-explorer/issues/3459#issuecomment-1136144989_

### PR DESCRIPTION
**Pull request by dkm**
When compiling to binary or running the executable, extra options are inserted,
breaking some weak asumption in Ada/GNAT on where in the list is the
inputFilename.

Override prepareArguments() for GNAT and (more) cleanly handle the
options (split between gnatmake, compiler, binder and linker).

Also use 'gnatmake' as main compiler executable instead of 'gnat'.

Fixes #3709

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

File: lib/compilers/ada.js [hunk 1]
```diff
@@ -53,91 +53,112 @@ export class AdaCompiler extends BaseCompiler {
...
+                continue;
+            }
+
+            if (part == 0) {
+                gnatmake_opts.push(a);
+            } else if (part == 1) {
+                compiler_opts.push(a);
+            } else if (part == 2) {
+                linker_opts.push(a);
+            } else if (part ==_3) {
```
Comment (partouf) [inline lib/compilers/ada.js:143]: `_3` typo?

Comment (dkm) [reply lib/compilers/ada.js]: Yes... Don't know why the linter catches this here and not locally :/

**Comment by dkm** [comment]
I've tested this locally as much as I could... GCC dumps are still working, so are the GNAT debug specific dumps, assembly, compile to binary, execute, IDE mode.

**Review by partouf — APPROVED** [review]
