### PR TITLE
Make 2024 the default edition for Rust >= 1.85

### LINKED ISSUE #7472: [BUG]: Rust 1.85.0 and later are using Rust 2021 edition instead of 2024
### Describe the bug

Rust's 2024 edition came out with Rust 1.85.0. The current default compiler options for 1.85, beta, and nightly are `-C debuginfo=2 -o output.s --emit asm -Cllvm-args=--x86-asm-syntax=intel --crate-type rlib --color=always --edition 2021 example.rs`. Can you please correct `--edition 2021` to `--edition 2024` for 1.85.0 and later, beta, and nightly?

### Steps to reproduce

1. Visit [rust.godbolt.org](https://rust.godbolt.org).
2. Select Rust version 1.85.0, beta, or nightly.
3. View the command line arguments.
4. Note that the command line arguments include `--edition 2021`.

### Expected behavior

The command line arguments should include `--edition 2024` instead of `--edition 2021`.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by narpfel**
Resolves #7472.

### CODE REVIEW

File: lib/compilers/rust.ts [hunk 1]
```diff
@@ -122,11 +122,15 @@ export class RustCompiler extends BaseCompiler {
         if (possibleEditions.length > 0) {
             let defaultEdition: undefined | string;
             if (!this.compiler.semver || this.isNightly()) {
-                defaultEdition = '2021';
+                defaultEdition = '2024';
```
Comment (AbrilRBS) [inline lib/compilers/rust.ts:125]: Just pointing out for other reviewers that this is not the default edition rustc uses,
but the latest stable one:

From rust 1.86.0:
```
--edition 2015|2018|2021|2024
                        Specify which edition of the compiler to use when
                        compiling code. The default is 2015 and the latest
                        stable edition is 2024.
```

File: lib/compilers/rust.ts [hunk 2]
```diff
@@ -122,11 +122,15 @@ export class RustCompiler extends BaseCompiler {
...
             } else {
                 const compilerVersion = new SemVer(this.compiler.semver);
-                if (compilerVersion.compare('1.56.0') >= 0) {
+                if (compilerVersion.compare('1.85.0') >= 0) {
+                    defaultEdition = '2024';
+                } else if (compilerVersion.compare('1.56.0') >= 0) {
                     defaultEdition = '2021';
+                } else if (compilerVersion.compare('1.31.0') >= 0) {
+                    defaultEdition = '2018';
```
Comment (AbrilRBS) [inline lib/compilers/rust.ts:133]: This would change old links created for these older versions to now use 2018, where previously nothing was passed and therfore 2015 was previously used (afaik? 1.86 seems to imply that 2015 is still the default unless otherwise stated).


Would this create issues with such old links that would have not defined 2015 explicitly and now would compile with 2018?

**Review by AbrilRBS — COMMENTED** [review]
Thanks! One comment regarding the default/stable edition for old versions, otherwise this seems to follow what we've been doing regarding rust editions until now :)

File: lib/compilers/rust.ts (hunk 2 above)
Comment (narpfel) [reply lib/compilers/rust.ts:133]: > This would change old links created for these older versions to now use 2018,

Would it? As far as I understand the code, this only affects which edition will be selected by default for the edition override setting. E. g. for this link https://godbolt.org/z/s3d5qqo3E there is no edition override selected, so even though `beta`’s `defaultEdition` is 2024, this has no effect on this link.

**Comment by narpfel** [comment]
It seems that the output format for `--help` has changed for `nightly` recently:
```
        --edition <2015|2018|2021|2024|future>
                        Specify which edition of the compiler to use when
                        compiling code. The default is 2015 and the latest
                        stable edition is 2024.
```
so this regex doesn’t match anymore: https://github.com/compiler-explorer/compiler-explorer/blob/0081f3a9ee7d3804612d0d73519a39cc861ebbe8/lib/compilers/argument-parsers.ts#L848

**Comment by narpfel** [comment]
> so this regex doesn’t match anymore

Resolved by #7652.

**Comment by partouf** [comment]
For some reason this doesn't seem to work. When I go to rust.godbolt.org and reset the layout, the default selected compiler is Rust 1.86, but the automatically selected Edition is 2021 instead of 2024

File: lib/compilers/rust.ts (hunk 2 above)
Comment (partouf) [reply lib/compilers/rust.ts:133]: Overrides are set to the defaults when they are missing from the State of the link. https://github.com/compiler-explorer/compiler-explorer/blob/main/static/compiler-shared.ts#L57
In old links this information was not stored in the state and as such the default will apply.

However, this has also happened in the past when this feature was first introduced, and so harm was done either way.

So I think this is acceptable.

Comment (narpfel) [reply lib/compilers/rust.ts:133]: I see. It’s probably better to remove this again then, given that I think it’s pretty unlikely that a lot of people (or even a few people) will use Rust <= 1.55 for new stuff.

Comment (narpfel) [reply lib/compilers/rust.ts]: I removed this in https://github.com/compiler-explorer/compiler-explorer/pull/7649/commits/e186970a92c823d67ce60be662658e16b9cacd2b.
