### PR TITLE
Fixes compiler init order by using initializeStateDependentProperties

### LINKED ISSUE #4207: [BUG]: Clone Compiler leaves the compiler flags field blank
### Describe the bug

see title

### Steps to reproduce

- Type anything that affects output in compiler options field (-O2, --help, -xc, --not-an-option, whatever)
- Add new -> Clone Compiler
- The new compiler has the same output (or lack thereof) as the original, but the compiler options field is empty

### Expected behavior

Slightly less empty compiler options field

### Reproduction link

Not applicable

### Screenshots

image

### Operating System

Lubuntu 22.04

### Browser version

Firefox 106

### PR DESCRIPTION
**Pull request by RubenRBS**
The options were being properly passed in the state, but the UI was being initialized before the value was set to the member, causing it not to be displayed.

Closes #4207

### CODE REVIEW

File: static/options.interfaces.ts [hunk 1]
```diff
@@ -51,12 +51,13 @@ export type LibsPerRemote = Record<string, LanguageLibs>;
 export type Options = {
     libs: Libs;
     remoteLibs: LibsPerRemote;
-    languages: Record<string, Language>;
```
Comment (RubenRBS) [inline static/options.interfaces.ts:54]: This is extra. Only the compileOptions addition is releated to the fix, but better typings are always good

File: static/panes/compiler.ts [hunk 2]
```diff
@@ -388,6 +378,23 @@ export class Compiler extends MonacoPane<monaco.editor.IStandaloneCodeEditor, Co
...
+        this.compilerService = this.hub.compilerService;
+        this.sourceTreeId = state.tree ? state.tree : null;
+        if (this.sourceTreeId) {
+            this.sourceEditorId = null;
+        } else {
+            this.sourceEditorId = state.source || 1;
+        }
+        this.options = state.options || (options.compileOptions[this.currentLangId ?? ''] ?? '');
+
+        this.deviceViewOpen = !!state.deviceViewOpen;
```
Comment (RubenRBS) [inline static/panes/compiler.ts:391]: Please do not merge until I test that the device and selection still work. I can't test device without using staging

Comment (partouf) [reply static/panes/compiler.ts:391]: you can test it locally if you have Clang, ICX or NVCC

Comment (partouf) [reply static/panes/compiler.ts:391]: device viewer still works
