### PR TITLE
Unify types for tool args

### LINKED ISSUE #7195: [BUG]: Enabling a tool returns error 400
### Describe the bug

see title

json contains `"tools":[{"id":"PVS-Studio","args":[],"stdin":""}]`

### Steps to reproduce

see title v2.0

hitting the recompile button, or making any other change, makes it send `"tools":[{"id":"PVS-Studio","args":"","stdin":""}]` which works

### Expected behavior

200 ok

### Reproduction link

Not applicable

### Screenshots

image

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by mattgodbolt**
- Uses strings across the board in the UI part (no functional change here from before; all state is the same as it was before).
- Sends _arrays_ in the POST, using the same `splitArguments` code as the backend.
- Backend _still supports_ strings (though doesn't advertise), also using same `splitArguments`.
- Moves `splitArguments` into common utils, and rephrases to avoid unnecessary use of underscore and ES2021+ code.

Tested locally:
- with both old and new client code (ran new backend and old webcode to show sending strings still works)
- with creating and removing tool windows (checked with `ldd` locally)
- with various strings on the client `moo foo "this is bad" #moo` and even "error" things like `this is "badger` (with a missing close quote). All works as you'd expect

Happy to break the "move the splitArguments" code into a separate PR if that'd be easier to review separately.

Fixes #7195

### CODE REVIEW

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
Approved but Tests are failing, those need fixing first

**Comment by mattgodbolt** [comment]
Thanks and whoops! I did run a few tests :D Will draft for now and fix them later before merging!

File: shared/common-utils.ts [hunk 1]
```diff
@@ -99,3 +101,11 @@ function splitIntoChunks(s: string, chunkSize: number): string[] {
 export function addDigitSeparator(n: string, digitSeparator: string, chunkSize: number): string {
     return splitIntoChunks(n, chunkSize).join(digitSeparator);
 }
+
+export function splitArguments(options = ''): string[] {
+    // escape hashes first, otherwise they're interpreted as comments
```
Comment (junlarsen) [inline shared/common-utils.ts:106]: Maybe this is an indication this isn't the best package to use? It also seems it supports control characters https://github.com/ljharb/shell-quote/blob/main/parse.js

Can you add tests for how stuff like operators and piping behaves? https://github.com/ljharb/shell-quote/blob/main/test/op.js#L6

**Review by junlarsen — CHANGES_REQUESTED** [review]
Seems fine to me, but I would like more tests on the behavior of shell-quote

File: shared/common-utils.ts (hunk 1 above)
Comment (mattgodbolt) [reply shared/common-utils.ts:106]: I'll add them in a separate PR as this was almost purely code motion and I don't want to further muddy it.

Comment (mattgodbolt) [reply shared/common-utils.ts:106]: > Maybe this is an indication this isn't the best package to use? It also seems it supports control characters https://github.com/ljharb/shell-quote/blob/main/parse.js

I don't know that we want to support those? Maybe? It would be a change in behaviour for anyone with `\` in them (maybe Windows people?)

Comment (mattgodbolt) [reply shared/common-utils.ts:106]: Oh! That's 100% your point!!! :'( yes...

Comment (partouf) [reply shared/common-utils.ts:106]: Changing anything about this changes the API, people have never complained about it. They did complain one time where it got changed to split on space. Unless someone has a valid use-case for different behaviour, please do not change it.

**Comment by mattgodbolt** [comment]
Ok @junlarsen per Discord, I'm going to land this and then immediately look into the issue you raised. I hope that's ok!

File: shared/common-utils.ts (hunk 1 above)
Comment (mattgodbolt) [reply shared/common-utils.ts:106]: Don't worry, I added tons of tests and kept all the behaviour the same _except where it was absolutely bonkers_ before. (like the weird handling of pipe characters and the escaping of quote strings ?!).

The PR will be up for a while anyway. We can't be too afraid of breaking things that are beyond undocumented like "what happens if you pass an argument that has a pipe character followed by double backslash and a hash")
