### PR TITLE
Fix size computation under display:none

### LINKED ISSUE #4611: [BUG]: Control flow graph is ugly if recompiled while hidden
### Describe the bug

See title/steps

### Steps to reproduce

1. Visit godbolt.org
2. Reset code/UI
3. Swap the code for anything containing branches or conditionals
4. Add new -> Control flow graph
5. Grab the CFG panel's tab and drop it into the compiler panel, so they become tabs on the same panel
6. Switch to compiler
7. Recompile
8. Switch back

### Expected behavior

image
Actual behavior:
image

### Reproduction link

https://godbolt.org/z/dW8qE998o

### Screenshots

See above

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Closes  #4611

### CODE REVIEW

File: static/panes/cfg-view.ts [hunk 1]
```diff
@@ -190,6 +192,27 @@ export class Cfg extends Pane<CfgState> {
         this.exportPNGButton = this.domRoot.find('.export-png').first();
         this.estimatedPNGSize = unwrap(this.exportPNGButton[0].querySelector('.estimated-export-size'));
         this.exportSVGButton = this.domRoot.find('.export-svg').first();
+
+        // create a fake .graph-container .graph .block-container where we can compute block dimensions
```
Comment (partouf) [inline static/panes/cfg-view.ts:196]: can you please refactor this into a new function

Comment (jeremy-rifkin) [reply static/panes/cfg-view.ts:196]: Thank you that's a good idea

**Comment by dkm** [comment]
This is now live :rocket:
