### PR TITLE
Ensure a default language is provided for new editor panes

### LINKED ISSUE #4889: [BUG]: Popup with error when adding Editor
### Describe the bug

When clicking Add... ->  Source Editor

This error pops up:
Screenshot from 2023-03-20 11-57-47

### Steps to reproduce

-

### Expected behavior

Error should not be happening.
Editor does get added without issues aside from the popup, but c++ is always selected no matter what my Default language is.

Should actually select the default language by default. (obviously)

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #4889

### CODE REVIEW

File: static/panes/editor.ts [hunk 1]
```diff
@@ -595,7 +595,8 @@ export class Editor extends MonacoPane<monaco.editor.IStandaloneCodeEditor, Edit
         };
 
         const getEditorConfig = () => {
-            return Components.getEditor();
+            // TODO(jeremy-rifkin): Can this.settings.defaultLanguage really be undefined?
```
Comment (partouf) [inline static/panes/editor.ts:598]: probably depends on the order of initialization, so in theory yes, but then something with the order of things should probably be fixed

**Review by partouf — APPROVED** [review]

**Comment by dkm** [comment]
This is now live! :rocket:
