### PR TITLE
Fix #3275 : move from compiler-opt-info to compiler-opt-info2

### LINKED ISSUE #3275: [BUG]: Internal server error on simple example
### Describe the bug

The attached link yields "internal server error"

### Steps to reproduce

click the link

### Expected behavior

Should Just Work™

### Reproduction link

https://godbolt.org/z/68dfa6Mxv

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**
`make check` passes.   

Following [this concern](https://twitter.com/OfekShilon/status/1496593807500062721) I checked the differences between the original compiler-opt-info github version and the npm version, and they seem non-functional. So my fork includes a fix based on the github version.

Not sure whether `yarn` is essential in the generated packages-lock, and don't think it matters.

Closes #3275

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
I wonder if it'd be better to integrate this logic into the CE source code directly rather than relying on an external module for it

**Comment by matsjla** [comment]
> I wonder if it'd be better to integrate this logic into the CE source code directly rather than relying on an external module for it

For a package spanning 80 lines in total this is probably better

**Comment by OfekShilon** [comment]
I don't know the history behind this package, I'll gladly delete it and spill its contents into CE.

**Comment by OfekShilon** [comment]
@jeremy-rifkin @matsjla  done as you guys suggested

File: lib/llvm-opt-transformer.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
+import {Transform, TransformCallback} from 'stream';
```
Comment (RubenRBS) [inline lib/llvm-opt-transformer.ts:1]: What license is this file even under?

**Review by RubenRBS — APPROVED** [review]

**Review by matsjla — APPROVED** [review]
LGTM after the license is added

File: lib/llvm-opt-transformer.ts (hunk 1 above)
Comment (matsjla) [reply lib/llvm-opt-transformer.ts:1]: https://github.com/jaredwy/compiler-opt-info/blob/master/LICENSE MIT, should probably be added to the header

Comment (mattgodbolt) [reply lib/llvm-opt-transformer.ts:1]: We used to have a check for this - did we lose it along the way?

Comment (RubenRBS) [reply lib/llvm-opt-transformer.ts:1]: Oh I bet we did not reenable it after the prettier changes

Comment (RubenRBS) [reply lib/llvm-opt-transformer.ts:1]: #3619 renables the license checks
