### PR TITLE
Make argument parsers instances instead of static classes

### LINKED ISSUE #8011: [BUG]: Opt Pipeline pane missing on production for LLVM compilers
### Describe the bug

The Opt Pipeline pane is not available on [godbolt.org](godbolt.org) for LLVM-based compilers.
I have tested on a local Compiler Explorer instance (latest main branch) and it works perfectly. 

### Steps to reproduce

1. Go to godbolt.org.
2. Select an LLVM-based compiler
3. Open the Add new… menu from the compiler pane.
4. Observe: Opt Pipeline is missing from the list 

### Expected behavior

The Opt Pipeline pane should be listed in the Add new… menu for supported LLVM compilers

### Reproduction link

Not applicable

### Screenshots

Image

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by mattgodbolt**
- Made parsers stateful instances instead of shared static state (for mllvm options). Fixes #8011 as this is caused by multiple clang-based compilers being run concurrently and stomping over each others' state.
- passes `Compiler` to the constructor, which removes some param passing
- Added some missing awaits
- Tried to get things less dependent on `examples`, only `go` needs it
- Spotted that `zig` c++ might have issues in discovery
- Fly-by fixed a broken go path in ppc64le_gl122
- removed a redundant override in coccinelle
- made the mojo parser actually use the parser it defined
- canonified tablegen's special method
- 

I changed the zig parser too but as best I can tell it was broken before (the `1` return value from the command it runs:)

```
ubuntu@ip-172-30-0-164:/infra/.deploy$ /opt/compiler-explorer/zig-0.14.1/zig c++ -mllvm --help-list-hidden /infra/.deploy/examples/c++/default.cpp -S -o /tmp/output.s
...
  --x86-use-vzeroupper                                                       - Minimize AVX to SSE transition penalty
  --xcore-max-threads=<number>                                               - Maximum number of threads (for emulation thread-local storage)
/infra/.deploy/examples/c++/default.cpp:1:1: error: FileNotFound
```
return code 1 (means it's not cached)

### CODE REVIEW

File: lib/compilers/argument-parsers.ts [hunk 1]
```diff
@@ -1088,12 +1059,12 @@ export class ZigCxxParser extends ClangParser {
...
-    static override getHiddenHelpOptions(exampleFile: string): string[] {
-        return ['c++', '-mllvm', '--help-list-hidden', exampleFile, '-S', '-o', '/tmp/output.s'];
+    static override getHiddenHelpOptions(): string[] {
+        return ['c++', '-mllvm', '--help-list-hidden', '-x', 'c++', '/dev/null', '-S', '-o', './output.s'];
     }
 
-    static override getStdVersHelpOptions(exampleFile: string): string[] {
-        return ['c++', '-std=c++9999999', exampleFile, '-S', '-o', '/tmp/output.s'];
+    static override getStdVersHelpOptions(): string[] {
+        return ['c++', '-std=c++9999999', '-x', 'c++', '/dev/null', '-S', '-o', './output.s'];
```
Comment (partouf) [inline lib/compilers/argument-parsers.ts]: why did you change to `./output.s`? you won't have write access to `./` at all

Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts]: everything runs in a temp dir (per the createAndUseTempDir: true) . this approach also used by golang

Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts]: ah! like you said in discord, only if isolate=true which is probably is not. I'll revert this (we need to fix golang then)

Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts]: Put back to `/tmp` :) thanks!

File: lib/compilers/argument-parsers.ts [hunk 2]
```diff
@@ -339,12 +323,10 @@ export class ClangParser extends BaseParser {
...
             const options = await this.getOptions(compiler, this.getMainHelpOptions().join(' '));
 
-            const filename = this.getExampleFilepath();
-
             this.mllvmOptions = new Set(
-                _.keys(await this.getOptions(compiler, this.getHiddenHelpOptions(filename).join(' '), false, true)),
+                _.keys(await this.getOptions(compiler, this.getHiddenHelpOptions().join(' '), false, true)),
             );
-            this.setCompilerSettingsFromOptions(compiler, options);
+            await this.setCompilerSettingsFromOptions(compiler, options);
```
Comment (mattgodbolt) [inline lib/compilers/argument-parsers.ts]: @partouf here - my only guess is... if somehow this took ages and we "discovered" and wrote the output before this completed (without the await)... but... seems unlikely

Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts]: Yeah and if that were true then "stack usage" etc would be broken and they're not.

Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts]: issue found, updated the description and checked in a "real fix". testing in staging...

**Comment by mattgodbolt** [comment]
COnfirmed fixed in staging. Will attend to comments now

File: lib/compilers/argument-parsers.ts [hunk 3]
```diff
@@ -241,119 +238,118 @@ export class GCCParser extends BaseParser {
...
 
-    static getMainHelpOptions(): string[] {
+    getMainHelpOptions(): string[] {
         return ['--help'];
     }
 
-    static getHiddenHelpOptions(exampleFile: string): string[] {
-        return ['-mllvm', '--help-list-hidden', exampleFile, '-c'];
+    getHiddenHelpOptions(): string[] {
+        return ['-mllvm', '--help-list-hidden', '-x', 'c++', '/dev/null', '-c'];
```
[the remark this answers is not in the document]
Comment (mattgodbolt) [reply lib/compilers/argument-parsers.ts:325]: nobody else used it

File: compiler-args-app.ts [hunk 4]
```diff
@@ -99,30 +100,30 @@ class CompilerArgsApp {
...
         console.error('Unknown parser type');
         process.exit(1);
     }
 
     async doTheParsing() {
         const parser = this.getParser();
-        await parser.parse(this.compiler);
+        await parser.parse();
         const options = this.compiler.possibleArguments.possibleArguments;
         if (parser.hasSupportStartsWith(options, '--target=')) {
```
[the remark this answers is not in the document]
Comment (mattgodbolt) [reply compiler-args-app.ts:135]: er? that was not a change. it works?

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
This is now live
