### PR TITLE
Warn when assembly output is in AT&T syntax (#4311)

### LINKED ISSUE #4311: [BUG]: tooltips don't take into account that non-Intel asm syntax and Intel asm syntax code show operands in reverse order
### Describe the bug

Well, it's a _documentation_ bug.

When the _Intel asm syntax_ checkbox is _un_checked, it appears to me that the various commands accepts operands in reverse order to when the it is checked, e.g. `andl    $70, %eax` vs `and     eax, 70`.

Now, from my perspective is natural to think of _first_ as _leftmost_, so the _destination_ operand is the _first_ in `andl    $70, %eax`, but the first in `and     eax, 70`.

The tooltips however seem not to adapt to this change.

### Steps to reproduce

1. visit https://godbolt.org/z/1YjTYqbf4
2. hover with the mouse on `andl`
3. see how _destination_ operand is referred to as the _first_ operand, which is on the other hand `$70`, unlikely to be a possible destination.

ce-wrong

### Expected behavior

When intel asm syntax is used, the first operand is correctly referred to as the destination:
ce-right

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by sean-garwood**
Assembly documentation tooltips always display Intel syntax information, but when the actual assembly output is in AT&T syntax, this can be confusing due to the reversed operand order (AT&T uses source, dest while Intel uses dest, source).

This change adds a warning to the tooltip when the assembly output is NOT in Intel syntax, informing users that the documentation pertains to Intel syntax.

The warning appears when:
- The user has not enabled the Intel syntax filter (filters.intel is false)
- The assembly output is therefore in AT&T syntax

The detection uses filters.isSet('intel') rather than compiler.intelAsm, ensuring we check the actual output syntax (what the user selected) rather than just whether the compiler supports Intel syntax.

Fixes #4311

refactor: move assembly-syntax type to frontend, remove from device-view

Move types/assembly-syntax.ts to static/assembly-syntax.ts since it's only used by frontend code (compiler.ts and device-view.ts), not backend.

Per CONTRIBUTING.md, types/ directory is for shared types used by both frontend (static/) and backend (lib/). Since AssemblySyntax is frontend-only, it belongs in static/.

Also removed syntax tracking from device-view entirely:
- Device assembly (CUDA PTX, GPU, etc.) doesn't have Intel/AT&T variants
- device-view was storing syntax as immutable state that never updated
- This would cause incorrect tooltips if user toggled syntax after opening
- Reverted device-view to match main branch (no syntax support)

Changes:
- Moved types/assembly-syntax.ts -> static/assembly-syntax.ts
- Updated import paths in compiler.ts
- Removed syntax field and imports from device-view.ts/.interfaces.ts

This means no unit tests are required per CONTRIBUTING.md guidelines (tests only required for server-side components in lib/).

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Sorry it's taken so long to get to this: I've been away and then started a new job. Trying to work through the backlog now!

File: static/panes/compiler.ts [hunk 1]
```diff
@@ -143,7 +144,10 @@ type Assembly = {
 
 const COMPILING_PLACEHOLDER = '<Compiling...>';
 
-// Disable max line count only for the constructor. Turns out, it needs to do quite a lot of things
+// Disable max line count only for the constructor. Turns out, it needs to do
```
Comment (mattgodbolt) [inline static/panes/compiler.ts]: was there a reason to reformat this line?

File: static/panes/compiler.ts [hunk 2]
```diff
@@ -3464,19 +3474,37 @@ export class Compiler extends MonacoPane<monaco.editor.IStandaloneCodeEditor, Co
     public static async getAsmInfo(
         opcode: string,
         instructionSet: InstructionSet,
+        syntax: AssemblySyntax = 'intel',
     ): Promise<AssemblyInstructionInfo | undefined> {
         const cacheName = `asm/${instructionSet}/${opcode}`;
         const cached = OpcodeCache.get(cacheName);
+
+        // Helper to add AT&T syntax warning to opcode data without mutating cache
```
Comment (mattgodbolt) [inline static/panes/compiler.ts:3489]: Nice solution to this.

File: static/panes/compiler.ts [hunk 3]
```diff
@@ -3464,19 +3474,37 @@ export class Compiler extends MonacoPane<monaco.editor.IStandaloneCodeEditor, Co
...
+                };
+            }
+            return data;
+        };
+
         if (cached) {
-            if (cached.found) return cached.data as AssemblyInstructionInfo;
+            if (cached.found) {
+                const cachedData = cached.data as AssemblyInstructionInfo;
+                // Return a copy with warnings added based on current syntax mode
```
Comment (mattgodbolt) [inline static/panes/compiler.ts]: I'm not sure this comment adds anything - the function name is very descriptive. Just `return addAttWEarningIfNeeded(cached.datat as AssmeblyInstructionIfo);` just as you do below.

**Review by mattgodbolt — COMMENTED** [review]
Basically LGTM! Sorry again for the delay. Just some comments/questions (exposing my lack of knowledge more than anything else)

File: static/panes/compiler.ts (hunk 1 above)
Comment (sean-garwood) [reply static/panes/compiler.ts]: Nope, looks like my system settings got in the way! Will revert.

File: static/panes/compiler.ts (hunk 2 above)
Comment (sean-garwood) [reply static/panes/compiler.ts:3489]: Thanks for the kind words!

File: static/panes/compiler.ts (hunk 3 above)
Comment (sean-garwood) [reply static/panes/compiler.ts]: Fixed.

**Comment by sean-garwood** [comment]
> Basically LGTM! Sorry again for the delay. Just some comments/questions (exposing my lack of knowledge more than anything else)

No worries! Hope the new job is going well. Sorry it took a bit for me to get to fixing these up.

EDIT: I did not squash the fixes commit; was not sure, but can squash and `git push --force-with-lease` if needed.

**Comment by mattgodbolt** [comment]
No need to squash! we do that on merge at the end :)

**Comment by partouf** [comment]
This is now live

**Comment by OfekShilon** [comment]
This warning now appears in languages that don't compile to native, but where we still supply IR documentation - python, java/kotlin, maybe others.

It also appears in the context-menu help, probably not in the way it was meant to:
image
(appears twice, without emph - raw `***`, and the bottom instance is a link for some reason)
@sean-garwood could you maybe look into it?
