### PR TITLE
Fix errorResponse return value

### LINKED ISSUE #4238: [BUG]: TypeError: e.map is not a function
Sentry Issue: [COMPILER-EXPLORER-A59](https://sentry.io/organizations/compiler-explorer/issues/3697353466/?referrer=github_integration)

```
TypeError: e.map is not a function. (In 'e.map((function(e){return o.__assign({sourcePane:t},e)}))', 'e.map' is undefined)
  at addSource (./static/panes/editor.ts:1398:60)
  at getAllOutputAndErrors (./static/panes/editor.ts:1431:31)
  at apply (./static/panes/editor.ts:1611:31)
  at emit (./static/event-hub.ts:69:37)
  at handleCompileRequestAndResponse (./static/panes/executor.js:579:19)
...
(7 additional frame(s) were not displayed)
```

This comes from having an executor open and then getting a 4xx, 5xx response in a compilation. We should probably check that the result is actually a valid response before using it elsewhere

### PR DESCRIPTION
**Pull request by RubenRBS**
Fixes #4238

### CODE REVIEW

File: static/panes/executor.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ Executor.prototype.resize = function () {
 };
 
 function errorResult(message) {
-    return {code: -1, stderr: message};
+    return {code: -1, stdout: [], stderr: [message]};
```
Comment (partouf) [inline static/panes/executor.js:180]: should this probably not be `stderr: [{text: message}]` or is it turned into something else at this point?

Comment (RubenRBS) [reply static/panes/executor.js:180]: Oh, there's a bug with the TS conversion here, you're totally right, I'll try to fix it

Comment (RubenRBS) [reply static/panes/executor.js]: Fixed now. Moved some types around too. At some point we need to review our API and check that the returns are actually what the types say they are
