### PR TITLE
More rust examples

### LINKED ISSUE #2133: [REQUEST] Make "Sum over array (Optimized)" example for Rust equivalent to the C++ version
Currently, the "Sum over array (Optimized)" example for C++ assumes that `input`'s length is a multiple of 64, however the Rust version of the example does not.

The Rust example should be changed to something like:

```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization
// assumes input's length is a multiple of 64
pub fn sum_array(input: &[i32]) -> i32 {
    if input.len() & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    input.iter().sum()
}
```

The generated assembly with `-C opt-level=3 -C target-cpu=native` on rustc 1.45.2 is then very similar to clang 10 on x86 with `-O3 -march=native` on the optimized sum over array example for C++.

Alternatively, the following example might be arguably more equivalent to the C++ version, however it is not really idiomatic Rust.

```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization
// assumes input's length is a multiple of 64
pub fn sum_array(input: &[i32]) -> i32 {
    let len = input.len();
    let input = input.as_ptr();

    if len & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    let mut sum = 0;
    for i in 0..len {
        sum += unsafe { *input.add(i) };
    }

    sum
}
````
As of rustc 1.45.2, this generates slightly fewer instructions than the idiomatic Rust version, but I think if the Rust example were to be changed, it should use the idiomatic version that was previously listed.

Another version which aligns `input`:
```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization

#[repr(align(64))]
pub struct Aligned<T: ?Sized>(T);

// assumes input is aligned on 64-byte boundary and that
// input's length is a multiple of 64.
pub fn sum_array(input: &Aligned<[i32]>) -> i32 {
    let len = input.0.len();
    let input = input.0.as_ptr();

    if len & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    let mut sum = 0;
    for i in 0..len {
        sum += unsafe { *input.add(i) };
    }

    sum
}
```

### LINKED ISSUE #2416: [BUG] Default Rust to binary rather than library
**Describe the bug**

Currently, godbolt expects Rust input to be a library. While handy, this isn't the default for either `cargo` or `rustc`, the two main tools for building Rust code. Rust programmers will have muscle memory and expect the default source they write to target binaries rather than libraries.

**To Reproduce**
Write a bit of Rust with a main, and notice how nothing useful is produced on the right hand side.

**Expected behavior**
Including the main function should be sufficient to see useful output on the right hand side.

**Link**
https://godbolt.org/z/q3YEY3

### PR DESCRIPTION
**Pull request by partouf**
* Fixes #2133
* Fixes #2416
* Includes example from #2106

### CODE REVIEW

File: examples/rust/default.rs [hunk 1]
```diff
@@ -2,3 +2,6 @@
 pub fn square(num: i32) -> i32 {
     num * num
 }
+
+// If you use `main()`, declare it as `pub` to see it in the output:
```
Comment (mattgodbolt) [inline examples/rust/default.rs:6]: Love it!

Missing a newline at the end of the file; can you add? Thanks!

**Review by mattgodbolt — APPROVED** [review]
3 bugs in one PR! legend :)

**Review by RubenRBS — APPROVED** [review]
