### PR TITLE
Fix #4654

### LINKED ISSUE #4654: LDC `generateAST` returns the wrong type
`generateAST` is supposed to return a `ResultLine[]` but `LDCCompiler.generateAST` returns a string (#4609)

### PR DESCRIPTION
**Pull request by OfekShilon**
Apparently AST for ldc is an abuse of terminology, as it doesn't produces anything resembling a syntax tree: https://github.com/dlang/dmd/pull/6556#issuecomment-282353400 . It is potentially meaningful only to ldc developers. Anyway the `generateAST` result type is fixed, along with some other small stuff around.

### CODE REVIEW

File: lib/compilers/ldc.ts [hunk 1]
```diff
@@ -99,37 +101,41 @@ export class LDCCompiler extends BaseCompiler {
...
         // Load the AST output from the `.cg` file.
         // Demangling is not needed.
-        const astFilename = output.inputFilename.concat('.cg');
+        const astFilename = result.inputFilename!.concat('.cg');
         try {
-            return await fs.readFile(astFilename, 'utf8');
+            const rawAST: string = await fs.readFile(astFilename, 'utf8');
+            return utils.parseOutput(rawAST, result.inputFilename);
+            // In theory we'd want to run this through this.llvmAst.processAst, but ldc's so-called-AST
+            // output is very different and processAst is moot:
```
Comment (mattgodbolt) [inline lib/compilers/ldc.ts:125]: Thanks for the link and commentary here.

File: lib/base-compiler.ts [hunk 2]
```diff
@@ -1214,7 +1214,7 @@ export class BaseCompiler implements ICompiler {
         return userOptions;
     }
 
-    async generateAST(inputFilename, options) {
+    async generateAST(inputFilename, options): Promise<ResultLine[]> {
```
Comment (mattgodbolt) [inline lib/base-compiler.ts:1217]: Thanks for updating the types here!

**Review by mattgodbolt — APPROVED** [review]
Very much appreciat ethe attention to detail @OfekShilon - thank you!
