### PR TITLE
Move static/libs-widget-ext.js to TypeScript

### LINKED ISSUE #3039: [BUG] Changing compiler on execution only view breaks library selection
**Describe the bug**
After selecting a library, if you change compiler, the library window remains empty until you reload the page.

**To Reproduce**
* Reset UI
* Close the default view and make an "execution only" view
* Click library and add "abseil trunk"
* Change compiler to another GCC
* Notice the "Library" button goes unselected
* Click Library and see "No libs configured for this language yet."
* Reload page
* Click library, see that it's re-populated.

**Expected behavior**
Libraries should be kept between compiler switches, where possible.

**Additional context**
Reported on Discord

### LINKED ISSUE #3088: [BUG]: Clang Execution Only context shows no available libraries
### Describe the bug

Enabling an execution only context for clang (tested with multiple versions) shows no libs available to be enabled (tested on chrome and edge). Changing the compiler to gcc or switching to a compiler context works as expected.

### Steps to reproduce

1. Visit godbolt.org
2. Add new -> Execution only
3.  Select x86-64 clang 10.0.1
4. Select libraries

### Expected behavior

Libraries should be available in all compilers

### Reproduction link

Not applicable

### Screenshots

_No response_

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by RubenRBS**
There might be some work still to be done, and the scope of the PR itself it a bit bigger than the ts move (But still releated to lib stuff)

Besides doing work towards completing #2981, it also

Closes #3039
Closes #3088

### CODE REVIEW

File: static/options.ts [hunk 1]
```diff
@@ -36,4 +38,4 @@ declare var __webpack_public_path__: string;
 
 __webpack_public_path__ = window.staticRoot;
 
-export const options = window.compilerExplorerOptions;
+export const options: CompilerExplorerOptions & {[key: string]: unknown} = window.compilerExplorerOptions as CompilerExplorerOptions & {[key: string]: unknown} ;
```
Comment (RubenRBS) [inline static/options.ts:41]: Surely there must be a better way to handle this until we fully move to TS, right?

File: static/panes/compiler.js [hunk 2]
```diff
@@ -1504,20 +1504,16 @@ Compiler.prototype.onLibsChanged = function () {
 };
 
 Compiler.prototype.initLibraries = function (state) {
-    var libUtils = new LibUtils();
```
Comment (RubenRBS) [inline static/panes/compiler.js:1507]: Does this play nice with older browesers?

File: static/panes/executor.js [hunk 3]
```diff
@@ -1038,7 +1036,16 @@ Executor.prototype.handleCompilationStatus = function (status) {
...
+    if (this.libsWidget) {
+        var filteredLibraries = {};
+        if (this.compiler) {
+            filteredLibraries = LibUtils.getSupportedLibraries(this.compiler.libsArr, this.currentLangId);
+        }
+
+        this.libsWidget.setNewLangId(this.currentLangId,
+            this.compiler ? this.compiler.id : false,
+            filteredLibraries);
+    }
```
Comment (RubenRBS) [inline static/panes/executor.js:1048]: This is the bit that fixes #3039

File: static/libs-widget-ext.ts [hunk 4]
```diff
@@ -0,0 +1,557 @@
...
+        this.showSelectedLibs();
+        this.showSelectedLibsAsSearchResults();
+        this.showFavorites();
+    }
+
+    updateButton() {
+        const selectedLibs = this.get();
+        let text = 'Libraries';
+        if (selectedLibs.length > 0) {
+            // TEST
```
Comment (RubenRBS) [inline static/libs-widget-ext.ts:126]: As I said, more work still needs to be done :)

File: static/libs-widget-ext.ts [hunk 5]
```diff
@@ -0,0 +1,557 @@
...
+            }
+
+            this.onChange();
+        });
+
+        return result;
+    }
+
+    addSearchResult(libId: string, library: Library) {
+        // Explain
```
Comment (RubenRBS) [inline static/libs-widget-ext.ts:354]: I know the difference between `JQuery<Node>` and `JQuery<HTMLElement>`, but without the any here so that the compiler ignores the types, it complains about `JQuery.Node being different from `Node` which, ok.
But then, what's the proper solution here?

File: static/libs-widget-ext.ts [hunk 6]
```diff
@@ -0,0 +1,557 @@
...
+
+            if (library.versions && library.versions.autodetect) return;
+
+            const card: any = this.newSearchResult(libId, library);
+            this.searchResults.append(card);
+        }
+    }
+
+    initLangDefaultLibs() {
+        const defaultLibs: string | null = options.defaultLibs[this.currentLangId];
```
Comment (RubenRBS) [inline static/libs-widget-ext.ts:430]: Could probably move it to the Options type definition

File: static/panes/executor.js (hunk 3 above)
Comment (RubenRBS) [reply static/panes/executor.js:1048]: And also #3088

File: static/libs-widget-ext.ts [hunk 7]
```diff
@@ -0,0 +1,557 @@
...
+    get(): {name: string, ver: any}[] {
+        const result = [];
+        const usedLibs = this.listUsedLibs();
+        for (let libId in usedLibs) {
+            result.push({name: libId, ver: usedLibs[libId]});
+        }
+        return result;
+    };
+
+    listUsedLibs(): {[libId: string]: string} {
```
Comment (supergrecko) [inline static/libs-widget-ext.ts:529]: Could use Record here

File: static/libs-widget-ext.ts [hunk 8]
```diff
@@ -0,0 +1,557 @@
...
+            for (let verId in library.versions) {
+                if (library.versions[verId].used) {
+                    libs[libId] = verId;
+                }
+            }
+        }
+        return libs;
+    };
+
+    getLibsInUse(): ({libId: string, versionId: string} & LibraryVersion)[] {
```
Comment (supergrecko) [inline static/libs-widget-ext.ts:543]: Probably best to refactor out this type

File: static/options.interfaces.ts [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+}
+
+
+export type LanguageLibs = {[libId: string]: Library};
+
+export type Libs = {[langId: string]: LanguageLibs};
+
+export interface Options {
+    libs: Libs;
+    defaultLibs: {[langId: string]: string | null};
```
Comment (supergrecko) [inline static/options.interfaces.ts:49]: Could use Record

File: static/panes/compiler.js (hunk 2 above)
Comment (supergrecko) [reply static/panes/compiler.js:1507]: Maybe it's just better to refactor LibUtils out of the class, we should probably not have a class with only static methods, instead export standalone functions

**Review by supergrecko — COMMENTED** [review]
I haven't looked too thoroughly through the code changes, but I've pointed out a couple typescript nits.

File: static/options.ts (hunk 1 above)
Comment (supergrecko) [reply static/options.ts]: Could we try something like this?

```patch
diff --git a/static/global.ts b/static/global.ts
index 10703670..1ec1e828 100644
--- a/static/global.ts
+++ b/static/global.ts
@@ -22,7 +22,12 @@
 // ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 // POSSIBILITY OF SUCH DAMAGE.
 
-type CompilerExplorerOptions = Record<string, unknown>;
+import { Libs } from './options.interfaces';
+
+type CompilerExplorerOptions = Record<string, unknown> & {
+    libs: Libs;
+    defaultLibs: Record<string, string | null>
+};
 
 declare global {
     export interface Window {
diff --git a/static/options.ts b/static/options.ts
index 4ce5e075..d92ebb5a 100644
--- a/static/options.ts
+++ b/static/options.ts
@@ -22,8 +22,6 @@
 // ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 // POSSIBILITY OF SUCH DAMAGE.
 
-import { Options } from './options.interfaces';
-
 const configElement = document.getElementById('config');
 
 window.httpRoot = configElement.getAttribute('httpRoot');
@@ -38,4 +36,4 @@ declare var __webpack_public_path__: string;
 
 __webpack_public_path__ = window.staticRoot;
 
-export const options: Options & {[key: string]: unknown} = window.compilerExplorerOptions as Options & {[key: string]: unknown} ;
+export const options = window.compilerExplorerOptions
```

Comment (RubenRBS) [reply static/options.ts]: Can you check if the what I changed works? I noticed the & right hand side was just options from Options

File: static/options.interfaces.ts [hunk 10]
```diff
@@ -23,23 +23,33 @@
 // POSSIBILITY OF SUCH DAMAGE.
 
 export interface LibraryVersion {
-    version: string;
+    alias: string[];
+    dependencies: string[];
     hidden: boolean;
+    libId: string;
+    liblink: string[];
```
Comment (partouf) [inline static/options.interfaces.ts:30]: Should we really be exposing these properties, as the client shouldn't really be doing anything with them.

**Review by partouf — CHANGES_REQUESTED** [review]

File: static/lib-utils.ts [hunk 11]
```diff
@@ -1,55 +1,64 @@
...
-            return this.copyAndFilterLibraries(allLibs, supportedLibrariesArr);
-        }
-        return allLibs;
+    return copiedLibraries;
+}
+
+export function getSupportedLibraries(supportedLibrariesArr: string[], langId: string) {
+    const allLibs = options.libs[langId];
+    if (supportedLibrariesArr && supportedLibrariesArr.length > 0) {
+        return this.copyAndFilterLibraries(allLibs, supportedLibrariesArr);
```
Comment (partouf) [inline static/lib-utils.ts:61]: There is no `this` here

File: static/options.ts (hunk 1 above)
Comment (supergrecko) [reply static/options.ts]: Sorry for the delay, looks good to me :+1:

File: static/options.interfaces.ts (hunk 10 above)
Comment (RubenRBS) [reply static/options.interfaces.ts:30]: libId is used by the compiler pane, but you're right, liblink could be safely removed

File: static/lib-utils.ts (hunk 11 above)
Comment (RubenRBS) [reply static/lib-utils.ts:61]: Good catch :)

File: static/options.interfaces.ts (hunk 10 above)
Comment (partouf) [reply static/options.interfaces.ts:30]: To be complete, these could be removed:
```
    libpath: string[];
    options: string[];
    path: string[];
    staticliblink: string[];
```

File: static/options.interfaces.ts [hunk 12]
```diff
@@ -0,0 +1,50 @@
...
+export interface LibraryVersion {
+    alias: string[];
+    hidden: boolean;
+    libId: string;
+    used: boolean;
+    version?: string;
+    versionId: string;
+}
+
+export interface Library {
```
Comment (supergrecko) [inline static/options.interfaces.ts:34]: I definitely think we should move the generic definitions of stuff like Library out somewhere in the future, but I think this is absolutely fine for now!

File: static/libs-widget-ext.ts [hunk 13]
```diff
@@ -0,0 +1,556 @@
...
+}
+
+export type CompilerLibs = Record<string, Library>;
+type LangLibs = Record<string, CompilerLibs>;
+type AvailableLibs = Record<string, LangLibs>;
+type LibInUse = {libId: string, versionId: string} & LibraryVersion;
+
+type FavLibraries = Record<string, string[]>;
+
+export class Widget {
```
Comment (supergrecko) [inline static/libs-widget-ext.ts:50]: Maybe we could rename this to LibrariesWidget? Widget sounds very generic

**Review by supergrecko — APPROVED** [review]
LGTM - I'm definitely not the most knowledgable around w/r/t the libs widget so I haven't been able to do thorough testing, but the code looks good.

File: static/libs-widget-ext.ts (hunk 13 above)
Comment (RubenRBS) [reply static/libs-widget-ext.ts:50]: You're right
