### PR TITLE
Prevent editor selection changes from overwriting shortlink url

### LINKED ISSUE #2016: [BUG] Short links get replaced by godbolt.org shortly after loading
**Describe the bug**
After clicking a short link, the URL bar continues to show /z/blah, but then will shortly revert to just godbolt.org. This makes it tricky to (e.g.) copy paste having opened on one device and send to another.

**To Reproduce**
Open a short link. wait... tab away, etc. Note the URL loses the /z/blah

**Expected behavior**
The /z/blah should remain until something changes in the page to invalidate it.

**Additional context**
Reported over twitter: https://twitter.com/Donzanoid/status/1270321725205553152

### PR DESCRIPTION
**Pull request by apmorton**
fixes #2016

I hate it, but it works
🤷

### CODE REVIEW

File: static/main.js [hunk 1]
```diff
@@ -273,6 +274,26 @@ function initPolicies(options) {
...
+        }
+
+        if (component.componentState) {
+            Object.keys(component.componentState)
+                .filter(function (key) { return keysToRemove.includes(key); })
+                .forEach(function (key) { delete component.componentState[key]; });
+        }
+    }
+
+    config = cloneDeep(config);
```
Comment (partouf) [inline static/main.js:292]: I'm wondering if this is needed, as toConfig() already makes new objects

Comment (apmorton) [reply static/main.js:292]: In my testing it was needed, toConfig seems to pass us references to some objects rather than copies?

I was a bit confused why I needed it as well having read the implementation of toConfig, so maybe I am wrong here.

Comment (partouf) [reply static/main.js:292]: ah ok, can't be helped then

Comment (RabsRincon) [inline static/main.js:292]: For objects such as our state, isn't it smaller to do `JSON.parse(JSON.stringify(config))`?

Comment (apmorton) [reply static/main.js:292]: I didn't do any of my own measurements, but the general consensus on some stack overflow posts was that json stringify/parse was slower than other options, and this code will execute quite frequently.

Comment (RabsRincon) [reply static/main.js:292]: Huh, I thought the opposite was true! Good to know then :)
