### PR TITLE
Actually use the setting style in the format api

### LINKED ISSUE #3089: [BUG]: Clang-format base style option has no effect
### Describe the bug

Changing clang-format style option has no effect. Always a default one is used (maybe google or llvm).

### Steps to reproduce

1. Enter this code in a new source file at godbolt.org:
```cpp
int main() {
    return 0;
}
```
2. Despite of which base style is chosen, the output of formatting document is:
```cpp
int main() { return 0; }
```

### Expected behavior

For example for GNU base style it should be formatted as:
```cpp
int
main ()
{
  return 0;
}
```

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Chrome/Edge 95, Firefox 78

### PR DESCRIPTION
**Pull request by supergrecko**
Fixes #3089

The formatter-registry will now use the site settings when querying the Format API. For compilers that do not support multiple styles, __DefeaultStyle is passed.

### CODE REVIEW

File: static/formatter-registry.ts [hunk 1]
```diff
@@ -56,29 +56,40 @@ const getFormattedCode = async ({ source, formatterId, base, tabWidth, useSpaces
     }
     // We had an error (either HTTP request error, or API error)
     // Figure out which it is, show it to the user, and reject the promise
-    const cause = (res.status === 200) ? body.answer : res.statusText;
+    const cause = body?.answer ?? res.statusText
```
Comment (supergrecko) [inline static/formatter-registry.ts:59]: This logic is better for when the API returns 422 or similar

**Review by RubenRBS — APPROVED** [review]

**Comment by partouf** [comment]
this is live
