### PR TITLE
Fix Python argument order

### LINKED ISSUE #4236: [BUG]: Cannot add switches to python interpreter
### Describe the bug

Adding "-O" does not work when trying to run python in optimized mode

### Steps to reproduce

add "-O" to the "Compiler options"

### Expected behavior

Godbolt runs python in optimized mode

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by RubenRBS**
In #3496 we fixed an issue regarding the order of arguments passed to the compiler, but this broke compilers that relied on the output from `optionsForFilters` (And probably the `.options` property) to be to have the `inputFilename` as the next argument, as is the case for Python.

This fixes it by overriding the order method in Python's compiler and restoring the old order.

Closes #4236

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks

**Comment by mattgodbolt** [comment]
Oops I pressed the wrong button

File: lib/compilers/carbon.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export class CarbonCompiler extends BaseCompiler {
 
     constructor(compilerInfo, env) {
         super(compilerInfo, env);
-        this.compiler.demangler = null;
```
Comment (mattgodbolt) [inline lib/compilers/carbon.js:36]: unrelated?

File: lib/compilers/python.ts [hunk 2]
```diff
@@ -22,33 +22,35 @@
...
+    private readonly disasmScriptPath: string;
+
     static get key() {
         return 'python';
     }
 
     constructor(compilerInfo, env) {
         super(compilerInfo, env);
-        this.compiler.demangler = null;
+        this.compiler.demangler = '';
```
Comment (mattgodbolt) [inline lib/compilers/python.ts:40]: unrelated? (or just cleaning up while you're here?)

**Review by mattgodbolt — APPROVED** [review]
LGTM - thanks! The cleanup stuff's fine, I was just a bit confused for a mo
