### PR TITLE
Reset stream styles between outputs

### LINKED ISSUE #3659: [BUG]: Bug with ansi color processing
### Describe the bug

The first time this code https://godbolt.org/z/evGE6f7Ga is run it's colored properly as 
image
When the code is rerun the pink color is still applied at the beginning
image

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

-

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #3659

### CODE REVIEW

File: test/ansi-to-html-tests.js [hunk 1]
```diff
@@ -68,4 +68,17 @@ describe('ansi-to-html', () => {
         const filter = new Filter(filterOpts);
         filter.toHtml('\x1B[7mhello').should.equal('hello');
     });
+
+    // tests for #3659
```
Comment (RubenRBS) [inline test/ansi-to-html-tests.js:72]: Love it, thanks

**Review by RubenRBS — APPROVED** [review]

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
now live
