### PR TITLE
Fix color scheme being overwritten on load

### LINKED ISSUE #2590: [BUG] Colour scheme setting not being saved
**Describe the bug**

Changing the color scheme is not currently persisted in the settings

**To Reproduce**

More > Settings. Navigate to the bottom, and change the Colour scheme to something other than the default. Reload the page. The scheme goes back to the default one.
The setting seems to be saved properly, but on page reload, a uiChange event is triggered and the setting seems to get overriden.

**Expected behavior**

Colour scheme setting is properly persisted across sessions.

**Link**

**Screenshots**

**Desktop**

 - OS:  Windows & Ubuntu
 - Browser  Firefox
 - Version  Latest

**Additional context**

This might be releated to other colour problems we have found, but I've been unable to pinpoint its origin.

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Closes #2590
This took a lot of printbugging for such a simple fix. At least a 10:1 ratio of console.log to diff lines (not including the renaming in fillColourSchemeSelector).

### CODE REVIEW

File: static/settings.ts [hunk 1]
```diff
@@ -222,6 +222,8 @@ export class Settings {
         this.addNumerics();
         this.addTextBoxes();
 
+        // The color scheme dropdown needs to be populated otherwise the .val won't stick and it'll default
+        this.fillColourSchemeSelector(this.root.find('.colourScheme'), this.settings.theme);
```
Comment (RubenRBS) [inline static/settings.ts:226]: 🤦 great catch

**Review by RubenRBS — APPROVED** [review]
