### PR TITLE
Respect tab width and tabs/spaces settings for format APIs

### LINKED ISSUE #2770: [BUG] Tab width ignored
**Describe the bug**
"Tab width" option in Settings is ignored when formatting code using Ctrl-F9 in source view.

**To Reproduce**
1. Open a new Compiler Explorer window (tried this in regular and incognito tabs, both on godbolt.org and on a local instance.)
2. Slightly modify the default "square" code to ensure it's not formatted to a single line:

```
// Type your code here, or load an example.
int square(int num) {
  int sqr = num * num;
  return sqr;
}
```

3. Verify in More -> Settings that "Tab width" is 4.
4. Press Ctrl-F9.

**Expected behavior**
Code should be indented with 4 spaces. However, it's indented with 2 spaces.

**Link**
Not sure it's necessary, but here it is anyway: https://godbolt.org/z/e8E7bGY1o

### PR DESCRIPTION
**Pull request by supergrecko**
Fixes #2770 

Site settings for tab width and tabs vs spaces are now being used when sent to the /api/format APIs.

This patch also includes some tiny internal refactoring on the bits related to the formatting API.

### CODE REVIEW

File: lib/base-formatter.js [hunk 1]
```diff
@@ -29,23 +29,30 @@ export class BaseFormatter {
...
+    /**
+     * Test if a formatting base style is valid for this formatter
+     */
     isValidStyle(style) {
         return this.formatterInfo.styles.includes(style);
     }
-
-    isOneTrueStyle() {
-        return this.formatterInfo.styles.length === 0;
-    }
```
Comment (supergrecko) [inline lib/base-formatter.js:50]: The formatter itself no longer cares if it is a "one true style" formatter. Implementor can express this in `isValidStyle`, and should handle this appropriately in `format`

File: static/formatter-registry.ts [hunk 2]
```diff
@@ -24,65 +24,80 @@
...
+import { getStoredSettings } from './settings';
+import { FormatRequestOptions } from './formatter-registry.interfaces';
+import { SiteSettings } from './settings.interfaces';
+
+const getFormattedCode = ({ source, formatterId, base, tabWidth, useSpaces }: FormatRequestOptions): Promise<string> => {
+    const alert = new Alert();
+    return new Promise((resolve, reject) => {
+        $.ajax(({
+            type: 'POST',
+            url: `${window.location.origin}${window.httpRoot}api/format/${formatterId}`,
```
Comment (supergrecko) [inline static/formatter-registry.ts:38]: Extracted the JQuery request out of the monaco logic.

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
this is now live
